# Generated by Django 4.0.5 on 2022-06-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('In stock', 'In stock'), ('Out of stock', 'Out of stock')], max_length=20)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('view', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('pass1', models.CharField(max_length=20)),
                ('pass2', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('pass1', models.CharField(max_length=20)),
                ('pass2', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=8)),
            ],
        ),
    ]
